project/Hakkers/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::namespace('Admin')->prefix('admin')->name('admin.')->group(function(){
    Route::resource('/planners', 'PlannerController');
    Route::resource('/monteurs', 'MonteurController');
    Route::resource('/users', 'UsersController');
    Route::get('/data', 'ExportController@index');
    Route::get('/data/download', 'ExportController@export');
});
Route::namespace('Planner')->prefix('planner')->name('planner.')->group(function(){
    Route::resource('/monteurs', 'MonteurController');
    Route::resource('/customers', 'CustomerController');
    Route::resource('/appointments', 'AppointmentController');
    Route::get('/appointments/{id}', 'AppointmentController@show');
});
Route::namespace('Monteur')->prefix('monteur')->name('monteur.')->group(function(){
    Route::resource('/appointments', 'MonteurController');
    Route::get('/appointments/{id}', 'MonteurController@show');
    Route::get('/appointments/{id}/start', 'MonteurController@start')->name('start.appointment');
        Route::get('/appointments/{id}/departure', 'MonteurController@departure')->name('departure.appointment');
        Route::get('/appointments/{id}/arrive', 'MonteurController@arrive')->name('arrive.appointment');
        Route::get('/appointments/{id}/finish', 'MonteurController@finish')->name('finish.appointment');
});

project/Hakkers/app/Monteur.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Monteur extends Model
{
    protected $fillable = [
        'name', 'function', 'email', 'user_id', 'appointment_id'
    ];
    public function Appointments() {
        return $this->hasMany(Appointment::class, "monteur_id", "id");
    }
}

project/Hakkers/app/Planner.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Planner extends Model
{
    protected $fillable = [
        'name', 'email', 'user_id',
    ];
}

project/Hakkers/app/Http/Controllers/Admin/MonteurController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Role;
use App\User;
use App\Planner;
use App\Monteur;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class MonteurController extends Controller
{
    /** This function will not showing the page without login */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $monteurs = Monteur::all();
        return view('admin.monteurs.index')->with('monteurs', $monteurs);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Monteur $monteur)
    {
        $roles = Role::all();

        return view('admin.monteurs.create')->with([
            'monteur' => $monteur,
            'roles' => $roles
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|max:255',
            'function' => 'required',
            'email' => 'required|email|unique:users,email',
            'password' => [
                'required', 'min:8', 'regex:/^.*(?=.*[a-z])(?=.*[A-Z])(?=.*\d)[a-zA-Z\d]{8,}$/' , 'confirmed'
            ],
        ]);

        $user = User::create([
            'name' => $request->input('name'),
            'email' => $request->input('email'),
            'password' => Hash::make($request->input('password')),
            'role_id' => 3,
        ]);
        $monteur = Monteur::create([
            'name' => $request->input('name'),
            'function' => $request->input('function'),
            'email' => $request->input('email'),
            'user_id' => $user->id,
            'appointment_id' => 0
        ]);

        return redirect()->route('admin.monteurs.index')->with('success', ''.$monteur->name.' is toegevoegd');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(Monteur $monteur)
    {

        return view('admin.monteurs.edit')->with([
            'monteur' => $monteur,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Monteur $monteur)
    {
        $user = User::find($monteur->user_id);

        $this->validate($request, [
            'name' => 'required|max:255',
            'function' => 'required',
            'email' => 'required|email|unique:users,email,'.$user->id,
        ]);

        $user->update([
            'name' => $request->input('name'),
            'email' => $request->input('email'),
            'password' => Hash::make($request->input('password')),
            'role_id' => 3,
        ]);

        $monteur->name = $request->input('name');
        $monteur->email = $request->input('email');
        $monteur->function = $request->input('function');
        $monteur->save();

        return redirect()->route('admin.monteurs.index')->with('success', ''.$monteur->name.' is bijgewerkt');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(Monteur $monteur)
    {
        $user = User::find($monteur->user_id);
//        $monteur->roles()->detach();
        $user->delete();
        $monteur->delete();

        return redirect()->route('admin.monteurs.index')->with('success', ''.$monteur->name.' is verwijderd');
    }
}

project/Hakkers/app/Http/Controllers/Admin/PlannerController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Role;
use App\User;
use App\Planner;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class PlannerController extends Controller
{
    /** This function will not showing the page without login */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $planners = Planner::all();

        return view('admin.planners.index')->with('planners', $planners);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Planner $planner)
    {
        $roles = Role::all();

        return view('admin.planners.create')->with([
            'planner' => $planner,
            'roles' => $roles
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|max:255',
            'email' => 'required|email|unique:users,email',
            'password' => [
                'required', 'min:8', 'regex:/^.*(?=.*[a-z])(?=.*[A-Z])(?=.*\d)[a-zA-Z\d]{8,}$/' , 'confirmed'
            ],
        ]);


        $user = User::create([
            'name' => $request->input('name'),
            'email' => $request->input('email'),
            'password' => Hash::make($request->input('password')),
            'role_id' => 2,
        ]);
        $planner = Planner::create([
            'name' => $request->input('name'),
            'email' => $request->input('email'),
            'user_id' => $user->id,
        ]);

        return redirect()->route('admin.planners.index')->with('success', ''.$planner->name.' is toegevoegd');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(Planner $planner)
    {
        $roles = Role::all();

        return view('admin.planners.edit')->with([
            'planner' => $planner,
            'roles' => $roles,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Planner $planner)
    {
        $user = User::find($planner->user_id);

        $this->validate($request, [
            'name' => 'required|max:255',
            'email' => 'required|email|unique:users,email,'.$user->id,
        ]);

        $user->update([
            'name' => $request->input('name'),
            'email' => $request->input('email'),
            'role_id' => 2,
        ]);

        $planner->name = $request->input('name');
        $planner->email = $request->input('email');
        $planner->save();

        return redirect()->route('admin.planners.index')->with('success', ''.$planner->name.' is bijgewerkt');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(Planner $planner)
    {
        $user = User::find($planner->user_id);
//        $planner->roles()->detach();
        $user->delete();
        $planner->delete();

        return redirect()->route('admin.planners.index')->with('success', ''.$planner->name.' is verwijderd');
    }
}

project/Hakkers/app/Http/Controllers/Monteur/MonteurController.php
<?php

namespace App\Http\Controllers\Monteur;

use App\Appointment;
use App\Customer;
use App\Http\Controllers\Controller;
use function GuzzleHttp\Promise\queue;
use Illuminate\Http\Request;
use App\Monteur;
use Carbon\Carbon;

class MonteurController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $customers = Customer::all();
        $monteur = Monteur::orderBy('id', 'desc')->first();
        $appointments = $monteur->Appointments;
        $appointments = Appointment::orderBy('created_at', 'desc')->get();
        $today = Carbon::today()->toDateString();
        $tomorrow = Carbon::tomorrow()->toDateString();


        return view('monteur.appointments.index')->with([
            'appointments' => $appointments,
            'customers' => $customers,
            'monteur' => $monteur,
            'today' => $today,
            'tomorrow' => $tomorrow
        ]);
    }

    /** This function is to show the appointments */
    public function show(Appointment $appointment)
    {
        $customers = Customer::all();
        $monteur = Monteur::orderBy('id', 'desc')->first()->id;

        /* This variables calculate the working hours of the appointment  */
        $arrived = Carbon::parse($appointment->arrived_date);
        $finished = Carbon::parse($appointment->finished_date);
        $working_hours = $arrived->diffInSeconds($finished);
        $working_hours = gmdate('H,i', $working_hours);
        $working_hours = ltrim($working_hours, '0');

        return view('monteur.appointments.single')->with([
            'appointment' => $appointment,
            'customers' => $customers,
            'monteur' => $monteur,
            'working_hours' => $working_hours
        ]);
    }

    /** This function is to send the user to the options page */
    public function start($id)
    {
        $appointment = Appointment::where('id', $id)->first();

        return view('monteur.appointments.start')->with([
            'appointment' => $appointment,
        ]);
    }

    /** This function is to saving the date when the worker depart */
    public function departure($id)
    {

        $appointment = Appointment::where('id', $id)->first();
        $time = Carbon::now();
        $now = $time->toDateTimeString();

        $appointment->depart_date = $now;
        $appointment->save();

        return redirect()->to('/monteur/appointments/' . $appointment->id . '/start')->with('success','Monteur is vertokken');
    }

    /** This function is to saving the date when the worker arrived */
    public function arrive($id)
    {
        $appointment = Appointment::where('id', $id)->first();
        $mytime = Carbon::now();
        $now = $mytime->toDateTimeString();

        $appointment->arrived_date = $now;
        $appointment->save();

        return redirect()->to('/monteur/appointments/' . $appointment->id . '/start')->with('success','Monteur is Aangekomen');
    }

    /** This function is to saving the date when the worker finished */
    public function finish($id)
    {
        $appointment = Appointment::where('id', $id)->first();
        $mytime = Carbon::now();
        $now = $mytime->toDateTimeString();

        $appointment->finished_date = $now;
        $appointment->successful = '1';
        $appointment->save();

        return redirect()->to('/monteur/appointments/')->with('success','Monteur is Klaar');
    }
}

project/Hakkers/app/Http/Controllers/Planner/CustomerController.php
<?php

namespace App\Http\Controllers\Planner;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Customer;

class CustomerController extends Controller
{
    /** This function will not showing the page without login */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $customers = Customer::all();
        return view('planner.customers.index')->with('customers', $customers);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Customer $customer)
    {
        $customers = Customer::all();
        return view('planner.customers.create')->with('customer', $customer);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|max:255|unique:customers,name',
            'address' => 'required',
            'zipcode' => 'required',
            'city' => 'required',
            'phone' => 'required|min:10',
        ]);

        $customer = Customer::create([
            'name' => $request->input('name'),
            'address' => $request->input('address'),
            'zipcode' => $request->input('zipcode'),
            'city' => $request->input('city'),
            'phone' => $request->input('phone'),
        ]);

        return redirect()->route('planner.customers.index')->with('success', ''.$customer->name.' is toegevoegd');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(Customer $customer)
    {

        return view('planner.customers.edit')->with('customer', $customer);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Customer $customer)
    {
        $this->validate($request, [
            'name' => 'required|max:255|unique:customers,name,'.$customer->id,
            'address' => 'required',
            'zipcode' => 'required',
            'city' => 'required',
            'phone' => 'required|min:10',
        ]);

        $customer->name = $request->input('name');
        $customer->address = $request->input('address');
        $customer->zipcode = $request->input('zipcode');
        $customer->city = $request->input('city');
        $customer->phone = $request->input('phone');
        $customer->save();

        return redirect()->route('planner.customers.index')->with('success', ''.$customer->name.' is bijgewerkt');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(Customer $customer)
    {
        $customer->delete();

        return redirect()->route('planner.customers.index')->with('success', ''.$customer->name.' is verwijderd');
    }
}

project/Hakkers/resources/views/planner/monteurs/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Monteur toevoegen</div>
                    <div class="card-body">
                        <form action="{{  route('planner.monteurs.store', $monteur) }}" method="POST">
                            @csrf

                            <div class="form-group row">
                                <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Naam') }}</label>

                                <div class="col-md-6">
                                    <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}" required autocomplete="name" autofocus>

                                    @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-md-4 col-form-label text-md-right">{{ __('Functie') }}</label>
                                <div class="col-md-6">
                                    <input type="text" class="form-control @error('function') is-invalid @enderror" name="function">

                                    @error('function')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail') }}</label>

                                <div class="col-md-6">
                                    <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" required autocomplete="email">

                                    @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('Wachtwoord') }}</label>

                                <div class="col-md-6">
                                    <input id="password" type="password" class="form-control @error('password') is-invalid @enderror" name="password" required autocomplete="new-password">

                                    @error('password')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="password-confirm" class="col-md-4 col-form-label text-md-right">{{ __('Wachtwoord herhalen') }}</label>

                                <div class="col-md-6">
                                    <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required autocomplete="new-password">
                                </div>
                            </div>
                            <button type="submit" class="btn btn-success float-right">
                                Toevoegen
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

project/Hakkers/resources/views/planner/monteurs/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Monteur bewerken</div>
                    <div class="card-body">
                        <form action="{{  route('planner.monteurs.update', $monteur) }}" method="POST">
                            @csrf
                            {{ method_field('PUT') }}
                            <div class="form-group row">
                                <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Naam') }}</label>

                                <div class="col-md-6">
                                    <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ $monteur->name }}" required autocomplete="name" autofocus>

                                    @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-md-4 col-form-label text-md-right">{{ __('Functie') }}</label>
                                <div class="col-md-6">
                                    <input type="text" class="form-control @error('function') is-invalid @enderror" name="function" value="{{ $monteur->function }}">

                                    @error('function')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail') }}</label>

                                <div class="col-md-6">
                                    <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ $monteur->email }}" required autocomplete="email">

                                    @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>
                            <button type="submit" class="btn btn-success float-right">
                                Bewerken
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

project/Hakkers/resources/views/planner/monteurs/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Monteurs</div>

                    <div class="card-body">
                        <a href="{{ route('planner.monteurs.create') }}"><button type="button" class="btn btn-success btn-add">Monteur toevoegen</button></a>
                        <table class="table">
                            <thead>
                            <tr>
                                <th scope="col">Naam</th>
                                <th scope="col">Functie</th>
                                <th scope="col">E-mail</th>
                                <th scope="col"></th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($monteurs as $monteur)
                                <tr>
                                    <td>{{ $monteur->name }}</td>
                                    <td>{{  $monteur->function }}</td>
                                    <td>{{  $monteur->email }}</td>
                                    <td>
                                        <form action="{{ route('planner.monteurs.destroy', $monteur) }}" method="POST" class="float-right">
                                            @csrf
                                            {{ method_field('DELETE') }}
                                            <button type="submit" class="btn btn-danger delete-warning">Verwijderen</button>
                                        </form>
                                        <a href="{{ route('planner.monteurs.edit', $monteur->id) }}"><button type="button" class="btn btn-primary float-right btn-edit">Bewerken</button></a>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection