project/Hakkers/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::namespace('Admin')->prefix('admin')->name('admin.')->group(function(){
    Route::resource('/planners', 'PlannerController');
    Route::resource('/monteurs', 'MonteurController');
    Route::resource('/users', 'UsersController');
    Route::get('/data', 'ExportController@index');
    Route::get('/data/download', 'ExportController@export');
});
Route::namespace('Planner')->prefix('planner')->name('planner.')->group(function(){
    Route::resource('/monteurs', 'MonteurController');
    Route::resource('/customers', 'CustomerController');
    Route::resource('/appointments', 'AppointmentController');
    Route::get('/appointments/{id}', 'AppointmentController@show');
});
Route::namespace('Monteur')->prefix('monteur')->name('monteur.')->group(function(){
    Route::resource('/appointments', 'MonteurController');
    Route::get('/appointments/{id}', 'MonteurController@show');
    Route::get('/appointments/{id}/start', 'MonteurController@start')->name('start.appointment');
        Route::get('/appointments/{id}/departure', 'MonteurController@departure')->name('departure.appointment');
        Route::get('/appointments/{id}/arrive', 'MonteurController@arrive')->name('arrive.appointment');
        Route::get('/appointments/{id}/finish', 'MonteurController@finish')->name('finish.appointment');
});

project/Hakkers/app/Appointment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Appointment extends Model
{
    protected $fillable = [
        'customer_id', 'monteur_id', 'date', 'type', 'note', 'depart_date', 'arrived_date', 'finished_date'
    ];
    public function customer()
    {
        return $this->belongsTo('App\Customer', 'customer_id');
    }
    public function monteur()
    {
        return $this->belongsTo('App\Monteur', 'monteur_id');
    }
}

project/Hakkers/app/Monteur.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Monteur extends Model
{
    protected $fillable = [
        'name', 'function', 'email', 'user_id', 'appointment_id'
    ];
    public function Appointments() {
        return $this->hasMany(Appointment::class, "monteur_id", "id");
    }
}

project/Hakkers/app/Http/Controllers/Admin/MonteurController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Role;
use App\User;
use App\Planner;
use App\Monteur;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class MonteurController extends Controller
{
    /** This function will not showing the page without login */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $monteurs = Monteur::all();
        return view('admin.monteurs.index')->with('monteurs', $monteurs);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Monteur $monteur)
    {
        $roles = Role::all();

        return view('admin.monteurs.create')->with([
            'monteur' => $monteur,
            'roles' => $roles
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|max:255',
            'function' => 'required',
            'email' => 'required|email|unique:users,email',
            'password' => [
                'required', 'min:8', 'regex:/^.*(?=.*[a-z])(?=.*[A-Z])(?=.*\d)[a-zA-Z\d]{8,}$/' , 'confirmed'
            ],
        ]);

        $user = User::create([
            'name' => $request->input('name'),
            'email' => $request->input('email'),
            'password' => Hash::make($request->input('password')),
            'role_id' => 3,
        ]);
        $monteur = Monteur::create([
            'name' => $request->input('name'),
            'function' => $request->input('function'),
            'email' => $request->input('email'),
            'user_id' => $user->id,
            'appointment_id' => 0
        ]);

        return redirect()->route('admin.monteurs.index')->with('success', ''.$monteur->name.' is toegevoegd');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(Monteur $monteur)
    {

        return view('admin.monteurs.edit')->with([
            'monteur' => $monteur,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Monteur $monteur)
    {
        $user = User::find($monteur->user_id);

        $this->validate($request, [
            'name' => 'required|max:255',
            'function' => 'required',
            'email' => 'required|email|unique:users,email,'.$user->id,
        ]);

        $user->update([
            'name' => $request->input('name'),
            'email' => $request->input('email'),
            'password' => Hash::make($request->input('password')),
            'role_id' => 3,
        ]);

        $monteur->name = $request->input('name');
        $monteur->email = $request->input('email');
        $monteur->function = $request->input('function');
        $monteur->save();

        return redirect()->route('admin.monteurs.index')->with('success', ''.$monteur->name.' is bijgewerkt');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(Monteur $monteur)
    {
        $user = User::find($monteur->user_id);
//        $monteur->roles()->detach();
        $user->delete();
        $monteur->delete();

        return redirect()->route('admin.monteurs.index')->with('success', ''.$monteur->name.' is verwijderd');
    }
}

project/Hakkers/app/Http/Controllers/Monteur/MonteurController.php
<?php

namespace App\Http\Controllers\Monteur;

use App\Appointment;
use App\Customer;
use App\Http\Controllers\Controller;
use function GuzzleHttp\Promise\queue;
use Illuminate\Http\Request;
use App\Monteur;
use Carbon\Carbon;

class MonteurController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $customers = Customer::all();
        $monteur = Monteur::orderBy('id', 'desc')->first();
        $appointments = $monteur->Appointments;
        $appointments = Appointment::orderBy('created_at', 'desc')->get();
        $today = Carbon::today()->toDateString();
        $tomorrow = Carbon::tomorrow()->toDateString();


        return view('monteur.appointments.index')->with([
            'appointments' => $appointments,
            'customers' => $customers,
            'monteur' => $monteur,
            'today' => $today,
            'tomorrow' => $tomorrow
        ]);
    }

    /** This function is to show the appointments */
    public function show(Appointment $appointment)
    {
        $customers = Customer::all();
        $monteur = Monteur::orderBy('id', 'desc')->first()->id;

        /* This variables calculate the working hours of the appointment  */
        $arrived = Carbon::parse($appointment->arrived_date);
        $finished = Carbon::parse($appointment->finished_date);
        $working_hours = $arrived->diffInSeconds($finished);
        $working_hours = gmdate('H,i', $working_hours);
        $working_hours = ltrim($working_hours, '0');

        return view('monteur.appointments.single')->with([
            'appointment' => $appointment,
            'customers' => $customers,
            'monteur' => $monteur,
            'working_hours' => $working_hours
        ]);
    }

    /** This function is to send the user to the options page */
    public function start($id)
    {
        $appointment = Appointment::where('id', $id)->first();

        return view('monteur.appointments.start')->with([
            'appointment' => $appointment,
        ]);
    }

    /** This function is to saving the date when the worker depart */
    public function departure($id)
    {

        $appointment = Appointment::where('id', $id)->first();
        $time = Carbon::now();
        $now = $time->toDateTimeString();

        $appointment->depart_date = $now;
        $appointment->save();

        return redirect()->to('/monteur/appointments/' . $appointment->id . '/start')->with('success','Monteur is vertokken');
    }

    /** This function is to saving the date when the worker arrived */
    public function arrive($id)
    {
        $appointment = Appointment::where('id', $id)->first();
        $mytime = Carbon::now();
        $now = $mytime->toDateTimeString();

        $appointment->arrived_date = $now;
        $appointment->save();

        return redirect()->to('/monteur/appointments/' . $appointment->id . '/start')->with('success','Monteur is Aangekomen');
    }

    /** This function is to saving the date when the worker finished */
    public function finish($id)
    {
        $appointment = Appointment::where('id', $id)->first();
        $mytime = Carbon::now();
        $now = $mytime->toDateTimeString();

        $appointment->finished_date = $now;
        $appointment->successful = '1';
        $appointment->save();

        return redirect()->to('/monteur/appointments/')->with('success','Monteur is Klaar');
    }
}

project/Hakkers/app/Http/Controllers/Planner/AppointmentController.php
<?php

namespace App\Http\Controllers\Planner;

use App\Appointment;
use App\Customer;
use App\Monteur;
use App\Http\Controllers\Controller;
use Carbon\Carbon;
use Illuminate\Http\Request;

class AppointmentController extends Controller
{
    /** This function will not showing the page without login */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $appointments = Appointment::all();
        $appointments = Appointment::orderBy('created_at', 'desc')->get();
        $monteurs = Monteur::all();
        $customers = Customer::all();

        return view('planner.appointments.index')->with([
            'appointments' => $appointments,
            'monteurs' => $monteurs,
            'customers' => $customers
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Appointment $appointment)
    {
        $appointments = Appointment::all();
        $monteurs = Monteur::all();
        $customers = Customer::all();

        return view('planner.appointments.create')->with([
            'appointment' => $appointment,
            'monteurs' => $monteurs,
            'customers' => $customers
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'date' => 'required|after:now'
        ]);

        $time = Carbon::now();
        $now = $time->toDateTimeString();
        $appointment = Appointment::create([
            'customer_id' => $request->input('customer'),
            'monteur_id' => $request->input('monteur'),
            'date' => $request->input('date'),
            'type' => $request->input('type'),
            'note' => $request->input('note'),
            'depart_date' => $now,
            'arrived_date' => $now,
            'finished_date' => $now,
        ]);

        return redirect()->route('planner.appointments.index')->with('success', 'Afspraak is ingepland');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(Appointment $appointment)
    {
        $appointments = Appointment::all();
        $monteurs = Monteur::all();
        $customers = Customer::all();

        $timestamp= $appointment->date;
        $splitTimeStamp = explode(" ",$timestamp);
        $date = $splitTimeStamp[0];
        $time = $splitTimeStamp[1];


        return view('planner.appointments.edit')->with([
            'appointment' => $appointment,
            'monteurs' => $monteurs,
            'customers' => $customers,
            'date' => $date,
            'time' => $time,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Appointment $appointment)
    {
        $this->validate($request, [
            'date' => 'required|after:now'
        ]);

        $appointment->customer_id = $request->input('customer');
        $appointment->monteur_id =$request->input('monteur');
        $appointment->date = $request->input('date');
        $appointment->type = $request->input('type');
        $appointment->note = $request->input('note');
        $appointment->save();

        return redirect()->route('planner.appointments.index')->with('success', 'Afspraak is bijgewerkt');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(Appointment $appointment)
    {
        $appointment->delete();

        return redirect()->route('planner.appointments.index')->with('success', 'Afspraak is verwijderd');
    }

    /** This function is to show the appointments */
    public function show(Appointment $appointment)
    {
        /* This variables calculate the working hours of the appointment  */
        $arrived = Carbon::parse($appointment->arrived_date);
        $finished = Carbon::parse($appointment->finished_date);
        $working_hours = $arrived->diffInSeconds($finished);
        $working_hours = gmdate('H,i', $working_hours);
        $working_hours = ltrim($working_hours, '0');

        return view('planner.appointments.single')->with([
            'appointment' => $appointment,
            'working_hours' => $working_hours
        ]);
    }
}

project/Hakkers/resources/views/monteur/appointments/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Afspraken</div>
                    <div class="card-body">
                        <table class="table">
                            <thead>
                            <tr>
                                <th scope="col">Klant</th>
                                <th scope="col">Datum en Tijd</th>
                                <th scope="col">Soort melding</th>
                                <th scope="col"></th>
                                <th scope="col"></th>
                            </tr>
                            </thead>
                            <tbody>
                            @if(count($appointments))
                            @foreach($appointments as $appointment)
                                @if($appointment->date > $today && $appointment->date < $tomorrow)
                                    @if($appointment->type == 'spoed' && $appointment->successful == '0')
                                        <audio id="play_audio" controls autoplay>
                                            <source src="/audio/alert.mp3" type="audio/mpeg">
                                            Your browser does not support the audio element.
                                        </audio>
                                        <div class="spoed-message">
                                            <p>Er is een spoed afspraak!</p>
                                        </div>
                                    @endif
                                    <tr class="clickable-row
                                            @if($appointment->type == "nieuw")
                                            nieuw
                                            @elseif ($appointment->type == "storing")
                                            storing
                                            @elseif ($appointment->type == "spoed")
                                            spoed
                                            @endif" data-href="/monteur/appointments/{{$appointment->id}}">
                                        <td>{{ $appointment->customer->name }}</td>
                                        <td>{{  $appointment->date }}</td>
                                        <td>{{  $appointment->type }}</td>
                                        <td>@if ($appointment->successful == '1')
                                                <i class="fas fa-check-circle"></i>
                                                @endif
                                        </td>
                                        <td></td>
                                    </tr>
                                @endif
                            @endforeach
                                @else
                                <p>Er zijn geen afspraken ingepland.</p>
                            @endif
                            </tbody>
                        </table>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

project/Hakkers/resources/views/monteur/appointments/single.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header @if($appointment->type == "nieuw")
                            nieuw
                            @elseif ($appointment->type == "storing")
                            storing
                            @elseif ($appointment->type == "spoed")
                            spoed
                            @endif">
                    </div>

                    <div class="card-body">
                        <h2>Afspraak nummer #{{ $appointment->id }}</h2>
                        <p></p>
                        <p><strong>Klant: </strong>{{ $appointment->customer->name }}</p>
                        <p><strong>Monteur: </strong>{{ $appointment->monteur->name }}</p>
                        <p><strong>Adres: </strong>{{ $appointment->customer->address }} {{ $appointment->customer->zipcode }} {{ $appointment->customer->city }}</p>
                        <p><strong>Tel: </strong>{{ $appointment->customer->phone }}</p>
                        <p><strong>Datum en Tijd: </strong>{{ $appointment->date }}</p>
                        <p><strong>Soort melding: </strong>{{ $appointment->type }}</p>
                        <p><strong>Notitie: </strong>{{ $appointment->note }}</p>

                        @if ($appointment->created_at != $appointment->depart_date)
                            <table class="table">
                                <thead>
                                <tr>
                                    <th scope="col">Vertrekt</th>
                                    <th scope="col">Aangekomen</th>
                                    <th scope="col">Klaar</th>
                                    <th>Gewerkte uren</th>
                                </tr>
                                </thead>
                                <tbody>
                                    <td>{{ $appointment->depart_date }}</td>
                                    <td>{{ $appointment->arrived_date }}</td>
                                    <td>{{ $appointment->finished_date }}</td>
                                    <td>{{ $working_hours }}</td>
                                </tbody>
                            </table>
                        @endif

                        @if ($appointment->successful != 1)
                        <a href="{{ route('monteur.start.appointment', $appointment->id) }}"><button type="button" class="btn btn-primary float-left">Start</button></a>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

project/Hakkers/resources/views/monteur/appointments/start.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Afspraak van {{ $appointment->customer->name }}</div>
                    <div class="row start-actions-container">
                        <form class="col" action="{{route('monteur.departure.appointment', $appointment->id)}}">
                            {{ csrf_field() }}
                            {{ method_field('POST') }}
                            <button type="submit" class="btn btn-primary" onclick="depart()">Vertrekken</button>

                        </form>
                        <form class="col" action="{{route('monteur.arrive.appointment', $appointment->id)}}">
                            {{ csrf_field() }}
                            {{ method_field('POST') }}
                            <button type="submit" class="btn btn-dark" onclick="depart()">Aangekomen</button>

                        </form>
                        <form class="col" action="{{route('monteur.finish.appointment', $appointment->id)}}">
                            {{ csrf_field() }}
                            {{ method_field('POST') }}
                            <button type="submit" class="btn btn-success" onclick="depart()">Klaar</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection