project/Hakkers/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::namespace('Admin')->prefix('admin')->name('admin.')->group(function(){
    Route::resource('/planners', 'PlannerController');
    Route::resource('/monteurs', 'MonteurController');
    Route::resource('/users', 'UsersController');
    Route::get('/data', 'ExportController@index');
    Route::get('/data/download', 'ExportController@export');
});
Route::namespace('Planner')->prefix('planner')->name('planner.')->group(function(){
    Route::resource('/monteurs', 'MonteurController');
    Route::resource('/customers', 'CustomerController');
    Route::resource('/appointments', 'AppointmentController');
    Route::get('/appointments/{id}', 'AppointmentController@show');
});
Route::namespace('Monteur')->prefix('monteur')->name('monteur.')->group(function(){
    Route::resource('/appointments', 'MonteurController');
    Route::get('/appointments/{id}', 'MonteurController@show');
    Route::get('/appointments/{id}/start', 'MonteurController@start')->name('start.appointment');
        Route::get('/appointments/{id}/departure', 'MonteurController@departure')->name('departure.appointment');
        Route::get('/appointments/{id}/arrive', 'MonteurController@arrive')->name('arrive.appointment');
        Route::get('/appointments/{id}/finish', 'MonteurController@finish')->name('finish.appointment');
});

project/Hakkers/resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Hakkers') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
<div id="app">
    <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
        <div class="container">
            <a class="navbar-brand" href="{{ url('/') }}">
                {{ config('app.name', 'Hakkers') }}
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Left Side Of Navbar -->
                <ul class="navbar-nav mr-auto">

                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="navbar-nav ml-auto">
                    <!-- Authentication Links -->
                    @guest
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                        </li>
{{--                        @if (Route::has('register'))--}}
{{--                            <li class="nav-item">--}}
{{--                                <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>--}}
{{--                            </li>--}}
{{--                        @endif--}}
                    @elseif (Auth()->user()->role_id === 2)
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('planner.appointments.index') }}">{{ __('Afspraken') }}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('planner.monteurs.index') }}">{{ __('Monteurs') }}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('planner.customers.index') }}">{{ __('Klanten') }}</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                    @csrf
                                </form>
                            </div>
                        </li>

                    @elseif (Auth()->user()->role_id === 3)
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('monteur.appointments.index') }}">{{ __('Afspraken') }}</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                    @csrf
                                </form>
                            </div>
                        </li>
                    @else
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('admin.planners.index') }}">{{ __('Planners') }}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('admin.monteurs.index') }}">{{ __('Monteurs') }}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/admin/data">{{ __('Afspraken') }}</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                    @csrf
                                </form>
                            </div>
                        </li>
                    @endguest
                </ul>
            </div>
        </div>
    </nav>

    <main class="py-4">
        @yield('content')
    </main>
</div>
@include('sweetalert::alert')

<div class="mt-5 pt-5 pb-5 footer">
    <div class="container">
        <div class="row">
            <div class="col-lg-5 col-xs-12 about-company">
                <h2>Hakkers</h2>
                <p class="pr-5 text-white-50">Voor al uw voorkomende installatiewerken</p>
                <p><a href="#"><i class="fa fa-facebook-square mr-1"></i></a><a href="#"><i class="fa fa-linkedin-square"></i></a></p>
            </div>
            <div class="col-lg-4 col-xs-12 location">
                <h4 class="mt-lg-0 mt-sm-4">Adres</h4>
                <p>Zijpendaalseweg 167, 6814 CJ Arnhem</p>
                <p class="mb-0"><i class="fa fa-phone mr-3"></i>(541) 754-3010</p>
                <p><i class="fa fa-envelope-o mr-3"></i>info@hakkers.com</p>
            </div>
            <div class="col-lg-3 col-xs-12 about-company">
                <img src="/images/login-photo.png" class="footer-img"/>
            </div>
        </div>
        <div class="row mt-5">
            <div class="col copyright">
                <p class=""><small class="text-white-50">© 2020. All Rights Reserved.</small></p>
            </div>
        </div>
    </div>
</div>

</body>
</html>